version: '2'
services:
  mongo:    
    container_name: mongo
    image: mongo:3.6.3-jessie
    #build:
    #  context: .
    #  dockerfile: ./Dockerfile_mongo
    #image: mongo:3.6.3-datoven
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin1234